Decompile sub_8002DB4
atasro2/pwaa1 pull request #46
Opened 2020-11-07 00:41 UTC by easyaspi314

Maybe I did something useful this time.

2020-11-07 01:37 UTC, easyaspi314 commented
Done with this for now, might work on the rest of asm/rom8002D6C.s in a later PR.

It doesn't appear to be that difficult, there is just a lot of it.

2020-11-10 21:19 UTC, atasro2 requested changes

2020-11-10 21:19 UTC, atasro2 commented on include/declarations.h
> +extern const u16 gUnknown_08015344[0x78/2];
These shouldn't be u16  as they are examination data and there already exists a struct for these in the code called `ExaminationData`

2020-11-10 21:19 UTC, atasro2 commented on src/rom8002D6C.c
> +#define COPY_EXAM_DATA(data) DmaCopy16(3, data, gExaminationData, sizeof(data))
i don't know about the name of this macro it loads that rooms examination data so COPY_EXAM_DATA sounds kinda misleading if you don't know what you're looking at i assume

2021-04-04 10:34 UTC, atasro2 commented
Obsoleted by #62

2021-04-04 10:34 UTC, closed without merging